version: "3.8"

env_file:
  - ./data-platform.env

networks:
  data-platform-network:
    name: data-platform-network
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.4
    container_name: zookeeper_local
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
    networks:
      - data-platform-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "${ZOOKEEPER_CLIENT_PORT}"]
      interval: 10s
      retries: 5

  broker:
    image: confluentinc/cp-kafka:8.1.0
    container_name: kafka_local
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
      KAFKA_LISTENERS: ${KAFKA_LISTENERS}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
    ports:
      - "9092:9092"
    volumes:
      - ./kafka/data:/var/lib/kafka/data
    networks:
      - data-platform-network
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      retries: 5

  schema-registry:
    image: confluentinc/cp-schema-registry:8.1.0
    container_name: schema_registry_local
    depends_on:
      broker:
        condition: service_healthy
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: ${KAFKA_ZOOKEEPER_CONNECT}
      SCHEMA_REGISTRY_HOST_NAME: schema_registry_local
    ports:
      - "8081:8081"
    networks:
      - data-platform-network

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka_ui_local
    depends_on:
      broker:
        condition: service_healthy
    ports:
      - "7777:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:9092
    networks:
      - data-platform-network

  minio:
    image: minio/minio
    container_name: minio_local
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
      MINIO_BROWSER: "on"
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio:/data
    networks:
      - data-platform-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio_local:9000/minio/health/live"]
      interval: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis_local
    ports:
      - "6379:6379"
    networks:
      - data-platform-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5

  postgres_airflow:
    image: postgres:15-alpine
    container_name: postgres_airflow
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./airflow/var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      - data-platform-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      retries: 5

  airflow:
    image: apache/airflow:2.8.2
    container_name: airflow_local
    depends_on:
      postgres_airflow:
        condition: service_healthy
      redis:
        condition: service_healthy
      broker:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW_EXECUTOR}
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${AIRFLOW_SQL_ALCHEMY_CONN}
      AIRFLOW__CELERY__BROKER_URL: ${AIRFLOW_CELERY_BROKER_URL}
      AIRFLOW__CORE__LOAD_EXAMPLES: ${AIRFLOW_LOAD_EXAMPLES}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/config:/opt/airflow/config
    ports:
      - "8085:8080"
    networks:
      - data-platform-network
    healthcheck:
      test: ["CMD", "airflow", "db", "check"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 60s

  greenplum:
    image: pro100filipp/greenplum-with-pxf
    container_name: greenplum_local
    hostname: greenplum-local
    restart: always
    ports:
      - "5433:5432"
    environment:
      GP_DB: ${GP_DB}
      GP_USER: ${GP_USER}
      GP_PASSWORD: ${GP_PASSWORD}
    volumes:
      - ./greenplum/data:/srv
    networks:
      - data-platform-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${GP_USER}", "-d", "${GP_DB}"]
      interval: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:9.10.0
    container_name: pgadmin_local
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - greenplum
    networks:
      - data-platform-network

  clickhouse:
    image: clickhouse/clickhouse-server:25.10
    container_name: clickhouse_local
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    ports:
      - "${CLICKHOUSE_HTTP_PORT}:${CLICKHOUSE_HTTP_PORT}"
      - "${CLICKHOUSE_TCP_PORT}:${CLICKHOUSE_TCP_PORT}"
    volumes:
      - ./clickhouse/var/lib/clickhouse:/var/lib/clickhouse
      - ./clickhouse/log:/var/log/clickhouse-server
    networks:
      - data-platform-network
    healthcheck:
      test: ["CMD", "bash", "-c", "clickhouse client --query='SELECT 1'"]
      interval: 10s
      retries: 5

  superset:
    image: apache/superset:latest
    container_name: superset_local
    environment:
      SUPERSET_ENV: ${SUPERSET_ENV}
    ports:
      - "${SUPERSET_PORT}:${SUPERSET_PORT}"
    volumes:
      - ./superset/config:/app/superset_home
    networks:
      - data-platform-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SUPERSET_PORT}/health"]
      interval: 10s
      retries: 5