networks:
  data-platform-network:
    driver: bridge

volumes:
  zookeeper_data:
  zookeeper_log:
  kafka_data:
  minio_data:
  redis_data:
  postgres_airflow_data:
  airflow_dags:
  airflow_plugins:
  greenplum_data:
  clickhouse_data:
  clickhouse_log:
  superset_data:
  oracle_data:
  pinot_controller:
  pinot_broker:
  pinot_server:
  portainer_data:
    
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper_local
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_4LW_COMMANDS_WHITELIST: "ruok,stat,conf,envi"
    networks:
      - data-platform-network
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181", "|", "grep", "-q", "imok"]
      interval: 5s
      timeout: 3s
      retries: 6
      start_period: 10s
      
  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka_local
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIR: /var/lib/kafka/data
    ports:
      - "9092:9092"
    networks:
      - data-platform-network
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - kafka_data:/var/lib/kafka/data
    stop_grace_period: 30s

  schema-registry:
    image: confluentinc/cp-schema-registry:7.0.1
    container_name: schema_registry_local
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
    ports:
      - "8081:8081"
    networks:
      - data-platform-network

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka_ui_local
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "7777:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - data-platform-network

  minio:
    image: minio/minio
    container_name: minio_local
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9005:9000"
      - "9006:9001"
    networks:
      - data-platform-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
      interval: 10s
      retries: 5
    volumes:
      - minio_data:/data

  redis:
    image: redis:7-alpine
    container_name: redis_local
    command: redis-server --requirepass redis123
    ports:
      - "6379:6379"
    networks:
      - data-platform-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis123", "ping"]
      interval: 10s
      retries: 5
    volumes:
      - redis_data:/data

  postgres_airflow:
    image: postgres:15-alpine
    container_name: postgres_airflow
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    networks:
      - data-platform-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
    volumes:
      - postgres_airflow_data:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.8.2
    container_name: airflow_webserver
    depends_on:
      postgres_airflow:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      REDIS_PASSWORD: redis123
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:redis123@redis:6379/0
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__FERNET_KEY: "K7j2m9xFvVwY0rR7K+Xp6Q=="
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
    ports:
      - "8085:8080"
    networks:
      - data-platform-network
    command: >
      bash -c "
        airflow db upgrade &&
        if ! airflow users list | grep -q admin; then
          airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin;
        fi &&
        airflow webserver
      "
    volumes:
      - airflow_dags:/opt/airflow/dags
      - airflow_plugins:/opt/airflow/plugins
    healthcheck:
      test: ["CMD", "airflow", "db", "check"]
      interval: 10s
      retries: 5
      start_period: 60s

  airflow-scheduler:
    image: apache/airflow:2.8.2
    container_name: airflow_scheduler
    depends_on:
      postgres_airflow:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      REDIS_PASSWORD: redis123
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:redis123@redis:6379/0
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__FERNET_KEY: "K7j2m9xFvVwY0rR7K+Xp6Q=="
    networks:
      - data-platform-network
    command: airflow scheduler
    volumes:
      - airflow_dags:/opt/airflow/dags
      - airflow_plugins:/opt/airflow/plugins

  airflow-worker:
    image: apache/airflow:2.8.2
    container_name: airflow_worker
    depends_on:
      postgres_airflow:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      REDIS_PASSWORD: redis123
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:redis123@redis:6379/0
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__FERNET_KEY: "K7j2m9xFvVwY0rR7K+Xp6Q=="
    networks:
      - data-platform-network
    command: airflow celery worker
    volumes:
      - airflow_dags:/opt/airflow/dags
      - airflow_plugins:/opt/airflow/plugins

  greenplum:
    image: pro100filipp/greenplum-with-pxf
    container_name: greenplum_local
    hostname: greenplum-local
    ports:
      - "5433:5432"
    environment:
      GP_USER: greenplum_user
      GP_PASSWORD: greenplum_password
      GP_DB: greenplum_db
    networks:
      - data-platform-network
    volumes:
      - greenplum_data:/srv

  clickhouse:
    image: clickhouse/clickhouse-server:25.10
    container_name: clickhouse_local
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: clickhouse123
      CLICKHOUSE_DB: default
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - data-platform-network
    healthcheck:
      test: ["CMD", "bash", "-c", "clickhouse client --query='SELECT 1'"]
      interval: 10s
      retries: 5
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_log:/var/log/clickhouse-server

  superset:
    image: apache/superset:latest
    container_name: superset_local
    environment:
      SUPERSET_SECRET_KEY: "NPu/q0Lzqcc7DDJ7Em5iUGKGsEElCz/q7cRPrP1buQU="
      _SUPERSET_USER: admin
      _SUPERSET_PASSWORD: admin
    ports:
      - "8088:8088"
    networks:
      - data-platform-network
    command: >
      bash -c "
        superset db upgrade &&
        if ! superset fab list-users | grep -q admin; then
          superset fab create-admin --username $${_SUPERSET_USER} --firstname Admin --lastname Admin --email admin@example.com --password $${_SUPERSET_PASSWORD};
        fi &&
        superset init &&
        superset run -p 8088 --host 0.0.0.0
      "

    volumes:
      - superset_data:/app/superset_home
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8088/health"]
      interval: 10s
      retries: 5
      start_period: 60s


  oracle:
    image: gvenzl/oracle-xe:21-faststart
    container_name: oracle_xe_local
    environment:
      - ORACLE_PASSWORD=oracle_password
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    restart: always
    networks:
      - data-platform-network


  pinot-controller:
    image: apachepinot/pinot:1.3.0
    container_name: pinot_controller_local
    command: "StartController -zkAddress zookeeper:2181"
    ports:
      - "9002:9000"
    networks:
      - data-platform-network
    volumes:
      - pinot_controller:/tmp/data/controller
    depends_on:
      zookeeper:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 30s

  pinot-broker:
    image: apachepinot/pinot:1.3.0
    container_name: pinot_broker_local
    command: "StartBroker -zkAddress zookeeper:2181"
    ports:
      - "8000:8000"
    networks:
      - data-platform-network
    depends_on:
      pinot-controller:
        condition: service_healthy
    volumes:
      - pinot_broker:/tmp/data/broker

  pinot-server:
    image: apachepinot/pinot:1.3.0
    container_name: pinot_server_local
    command: "StartServer -zkAddress zookeeper:2181"
    ports:
      - "8001:8001"
    networks:
      - data-platform-network
    depends_on:
      pinot-controller:
        condition: service_healthy
    volumes:
      - pinot_server:/tmp/data/server

  dozzle:
    container_name: dozzle_local
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8089:8080"

  portainer:
    image: portainer/portainer-ce:2.33.7
    ports:
      - "8066:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    restart: unless-stopped
