networks:
  data-platform-network:
    driver: bridge

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper_local
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_4LW_COMMANDS_WHITELIST: "ruok,stat,conf,envi"
    networks:
      - data-platform-network
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log


  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka_local
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    ports:
      - "9092:9092"
    networks:
      - data-platform-network
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - kafka_data:/var/lib/kafka/data

  schema-registry:
    image: confluentinc/cp-schema-registry:7.9.4
    container_name: schema_registry_local
    depends_on:
      - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: schema_registry_local
    ports:
      - "8081:8081"
    networks:
      - data-platform-network

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka_ui_local
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "7777:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - data-platform-network

  minio:
    image: minio/minio
    container_name: minio_local
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9005:9000"
      - "9006:9001"
    networks:
      - data-platform-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
      interval: 10s
      retries: 5
    volumes:
      - minio_data:/data

  redis:
    image: redis:7-alpine
    container_name: redis_local
    ports:
      - "6379:6379"
    networks:
      - data-platform-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
    volumes:
      - redis_data:/data

  postgres_airflow:
    image: postgres:15-alpine
    container_name: postgres_airflow
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    networks:
      - data-platform-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
    volumes:
      - postgres_airflow_data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.8.2
    container_name: airflow_local
    depends_on:
      - postgres_airflow
      - redis
      - kafka
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__FERNET_KEY: "K7j2m9xFvVwY0rR7K+Xp6Q=="
    ports:
      - "8085:8080"
    networks:
      - data-platform-network
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin || true &&
        airflow webserver &
        airflow scheduler
      "
    volumes:
      - airflow_dags:/opt/airflow/dags
      - airflow_plugins:/opt/airflow/plugins
    healthcheck:
      test: ["CMD", "airflow", "db", "check"]
      interval: 10s
      retries: 5
      start_period: 60s

  greenplum:
    image: pro100filipp/greenplum-with-pxf
    container_name: greenplum_local
    hostname: greenplum-local
    ports:
      - "5433:5432"
    environment:
      GP_DB: greenplum_db
      GP_USER: greenplum_user
      GP_PASSWORD: greenplum_password
    networks:
      - data-platform-network
    volumes:
      - greenplum_data:/srv

  pgadmin:
    image: dpage/pgadmin4:9.10.0
    container_name: pgadmin_local
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - greenplum
    networks:
      - data-platform-network

  clickhouse:
    image: clickhouse/clickhouse-server:25.10
    container_name: clickhouse_local
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - data-platform-network
    healthcheck:
      test: ["CMD", "bash", "-c", "clickhouse client --query='SELECT 1'"]
      interval: 10s
      retries: 5
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_log:/var/log/clickhouse-server

  superset:
    image: apache/superset:latest
    container_name: superset_local
    environment:
      SUPERSET_ENV: production
      SUPERSET_SECRET_KEY: NPu/q0Lzqcc7DDJ7Em5iUGKGsEElCz/q7cRPrP1buQU=
    ports:
      - "8088:8088"
    networks:
      - data-platform-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8088/health"]
      interval: 10s
      retries: 5
    volumes:
      - superset_data:/app/superset_home

volumes:
  zookeeper_data:
  zookeeper_log:
  kafka_data:
  minio_data:
  redis_data:
  postgres_airflow_data:
  airflow_dags:
  airflow_plugins:
  greenplum_data:
  clickhouse_data:
  clickhouse_log:
  superset_data:
